#Author
#Date
#Description
@TambahAkomodasi
Feature: feature to test tambah akomodasi functionality

  @TambahAkomodasi1
  Scenario Outline: Check valid input in all field
    Given User tambah akomodasi has opened the browser
    And User tambah akomodasi already in home page
    When User tambah akomodasi clicks on sidebar with tab name Kemitraan
    And User tambah akomodasi clicks on sidebar with dropdown tab name Akomodasi
    And User tambah akomodasi clicks on Tambah button
    And User tambah akomodasi mengisi "<nama>" "<deskripsi>" "<banner>" "<provinsi>" "<kota>" "<distrik>" "<desa>" "<alamat>" "<longitude>" "<latitude>" "<no_telp>" "<email>" "<harga>" "<rating>" "<fasilitas>" "<tipe>" "<harga_fasilitas>" dan "<thumbnail>"
    And User tambah akomodasi clicks on "<choice>" button
    Then User tambah akomodasi should be "<condition>" to see notifications Data Tersimpan

    Examples: 
      | nama                | deskripsi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | banner                         | provinsi   | kota            | distrik        | desa      | alamat                                                                              | longitude   | latitude   | no_telp      | email                         | harga   | rating | fasilitas                                                              | tipe              | harga_fasilitas | thumbnail                                  | choice  | condition |
      | Hotel Santika Garut | Selain standar dari Indonesia Care, semua tamu akan mendapatkan Wi-Fi gratis di semua kamar dan parkir gratis jika tiba dengan mobil. Terletak strategis di Cipanas yang merupakan bagian Garut, properti ini menempatkan Anda dekat dengan atraksi dan opsi restoran menarik. Jangan pulang dulu sebelum berkunjung ke Rumah Makan Cibiuk yang terkenal. Memiliki peringkat bintang-4, properti berkelas ini menyediakan akses ke kolam renang luar ruangan, pijat dan pusat kebugaran untuk para tamu di properti. | E:/Documents/Tugas/santika.jpg | JAWA BARAT | KABUPATEN GARUT | TAROGONG KALER | PANANJUNG | Jl. Cipanas Baru, Pananjung, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151 | 107.7354627 | -7.2027115 | 082622805990 | garut@reservation.santika.com | 1543750 |      5 | Bersih higienis, Check-in 24 jam, Pemandangan luar biasa , WiFi, Sauna | Kamar Twin Deluxe |          506000 | E:/Documents/Tugas/twin_deluxe_santika.jpg | Simpan  | able      |
      |                     | Selain standar dari Indonesia Care, semua tamu akan mendapatkan Wi-Fi gratis di semua kamar dan parkir gratis jika tiba dengan mobil. Terletak strategis di Cipanas yang merupakan bagian Garut, properti ini menempatkan Anda dekat dengan atraksi dan opsi restoran menarik. Jangan pulang dulu sebelum berkunjung ke Rumah Makan Cibiuk yang terkenal. Memiliki peringkat bintang-4, properti berkelas ini menyediakan akses ke kolam renang luar ruangan, pijat dan pusat kebugaran untuk para tamu di properti. | E:/Documents/Tugas/santika.jpg | JAWA BARAT | KABUPATEN GARUT | TAROGONG KALER | PANANJUNG | Jl. Cipanas Baru, Pananjung, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151 | 107.7354627 | -7.2027115 | 082622805990 | garut@reservation.santika.com | 1543750 |      5 | Bersih higienis, Check-in 24 jam, Pemandangan luar biasa , WiFi, Sauna | Kamar Twin Deluxe |          506000 | E:/Documents/Tugas/twin_deluxe_santika.jpg | Simpan  | not able  |
      | Hotel Santika Garut | Selain standar dari Indonesia Care, semua tamu akan mendapatkan Wi-Fi gratis di semua kamar dan parkir gratis jika tiba dengan mobil. Terletak strategis di Cipanas yang merupakan bagian Garut, properti ini menempatkan Anda dekat dengan atraksi dan opsi restoran menarik. Jangan pulang dulu sebelum berkunjung ke Rumah Makan Cibiuk yang terkenal. Memiliki peringkat bintang-4, properti berkelas ini menyediakan akses ke kolam renang luar ruangan, pijat dan pusat kebugaran untuk para tamu di properti. | E:/Documents/Tugas/santika.jpg | JAWA BARAT | KABUPATEN GARUT | TAROGONG KALER | PANANJUNG | Jl. Cipanas Baru, Pananjung, Kec. Tarogong Kaler, Kabupaten Garut, Jawa Barat 44151 | 107.7354627 | -7.2027115 | 082622805990 | garut@reservation.santika.com | 1543750 |      5 | Bersih higienis, Check-in 24 jam, Pemandangan luar biasa , WiFi, Sauna | Kamar Twin Deluxe |          506000 | E:/Documents/Tugas/twin_deluxe_santika.jpg | Kembali | not able  |
